trigger:
- main

stages:
- stage: Build
  displayName: Build node stage

  jobs:
  - job: Build_node
    displayName: Build job
    
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'
    
    - script: |
        npm install
      displayName: 'npm install'
    
    - script: |
        npm run build
      displayName: 'npm build'