trigger:
- main

stages:
- stage: Build
  displayName: Build node stage

  jobs:
  - job: Build_node
    displayName: Build job
    
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'
    
    - script: |
        npm install
      displayName: 'npm install'
      
    - script: |
        npm audit --registry=https://registry.npmjs.org/
      displayName: 'npm audit'
    
    - script: |
        npm run build
      displayName: 'npm build'
    
    - script: |
        ls -la
      displayName: 'show all folders' 

    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)'
        contents: 'build/**' 
        targetFolder: $(Build.ArtifactStagingDirectory)/npm
      displayName: 'Copy build/**'

    - script: |
        ls -la
      displayName: 'show all folders2' 

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/npm'
        artifactName: npm build output
      displayName: 'Publish npm artifact'

    - script: |
        ls -la
      displayName: 'show all folders3' 